cubes: ["cube1", "cube2"]

cube1:
  id: "cube1"
  size: [0.05, 0.05, 0.08]
  position: [0.2, 0.4, 0.3]
  orientation: [0.0, 0.0, 0.2, 1.0]

cube2:
  id: cube2
  size: [0.08, 0.08, 0.08]
  position: [0.4, 0.0, 0.1]
  orientation: [0.3, 0.7, 0.0, 1.0]

table1:
  id: table1
  size: [0.8, 0.8, 0.05]
  position: [0.5, 0.4, 0.200]
  orientation: [0.0, 0.0, 0.0, 1.0]

how_take_cube : 
  choice_face: 2 # 0:+X, 1:-X, 2:+Y, ...
  side_face : width_down # width or length

goal:
  position: [0.2, 0.4, 0.0]
  orientation: [0.3, 0.3, 0.3, 1.0]

how_place_cube :
  choice_face: 1   
  side_face: length      # contrôle la rotation dans le plan