robots:
  panda:
    manipulator_group: panda_manipulator
    gripper_group: panda_hand
    base_frame: world

  pr2:
    manipulator_group: right_arm  #ou left_arm
    gripper_group: right_gripper #ou left_gripper
    base_frame: base_link 

# robot sélectionné
robot: panda
