cube:
  size: [0.05, 0.05, 0.05]
  position: [0.3, 0.4, 0.0]
  orientation: [0.0, 0.6, 0.2, 0.3]

table:
  size: [0.8, 0.8, 0.05]
  position: [0.5, 0.4, 0.200]
  orientation: [0.0, 0.0, 0.0, 1.0]

goal:
  position: [0.3, 0.8, 0.6]
  orientation: [0.0, 0.0, 0.0, 1.0]